project:
  type: website
  output-dir: docs

website:
  title: "Sandra Tamakloe"
  navbar:
    left:
      - href: index.qmd
        text: "{{< fa house >}} Home"      
      - href: CV.qmd
        text: "{{< fa user-tie >}} CV"
        
    right: 
     - href: Contact.qmd
       text: "{{< fa envelope >}} Contact"
     - href: https://sandratamakloe.github.io/Microeconometrics-website/
       icon: github

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

